// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQg970rmFN8yYsg6525B0L2PxEpz7qGXQ',
    appId: '1:429494554981:android:509d6cf87ebc439288518c',
    messagingSenderId: '429494554981',
    projectId: 'clinic-inventory-app',
    databaseURL: 'https://clinic-inventory-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clinic-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNNHUIgPAEHKicrilkPeEWEOGNhNOqW2A',
    appId: '1:429494554981:web:3e23a1da7a3a2b1988518c',
    messagingSenderId: '429494554981',
    projectId: 'clinic-inventory-app',
    authDomain: 'clinic-inventory-app.firebaseapp.com',
    databaseURL: 'https://clinic-inventory-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'clinic-inventory-app.firebasestorage.app',
    measurementId: 'G-NK8M17FWM5',
  );
}
